Assignment_5_1_StarterCode/CIS174_TestCoreApp/Models/CreateAccountViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;


namespace CIS174_TestCoreApp.Models
{
    public class CreateAccountViewModel
    {
        public static List<SelectListItem> ItemsWithGroups { get; private set; }
        [Required]
        [Display(Name = "First Name")]
        [StringLength(25)]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        [StringLength(25)]
        [MinLength(2)]
        public string LastName { get; set; }

        [Range(1, 120)]
        public int Age { get; set; }

        [Range(typeof(DateTime), "1,1,1900", "12,31,2108")]
        public DateTime DateOfBirth { get; set; }

        [Required]
        [StringLength(100)]
        public string Email { get; set; }

        [Required]
        [Display(Name = "Confirm Password")]
        [Compare("ConfirmPassword")]
        public string Password { get; set; }

        [Required]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }


        public IEnumerable<string> SelectedValues { get; set; }
        public IEnumerable<SelectListItem> Items { get; set; }
        public static void SelectListsViewModel()

        {

            var country = new SelectListGroup { Name = "Country" };
            ItemsWithGroups = new List<SelectListItem>
            {
                new SelectListItem{Value= "USA", Text = "USA", Group = country },
                new SelectListItem { Value = "Mexico", Text = "Mexico", Group = country },
                new SelectListItem { Value = "Canada", Text = "Canada", Group = country },
            };
        }
    }
}

Assignment_5_1_StarterCode/CIS174_TestCoreApp/Models/Date.cs
namespace CIS174_TestCoreApp.Models
{
    public class Date
    {
    }
}

Assignment_5_1_StarterCode/CIS174_TestCoreApp/Models/ErrorViewModel.cs
using System;

namespace CIS174_TestCoreApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Assignment_5_1_StarterCode/CIS174_TestCoreApp/Models/HouseViewModel.cs
using CIS174_TestCoreApp.Models;

namespace DemoWebApi.Models
{
    public class HouseViewModel
    {
        public string Bedrooms { get; set; }
        public string SquareFeet { get; set; }
        public string DateBuilt { get; set; }
        public string Flooring { get; set; }

    }
}

Assignment_5_1_StarterCode/CIS174_TestCoreApp/Models/StudentModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;


namespace CIS174_TestCoreApp.Models
{
    public class StudentModel
    {
        [Required]
        [Display(Name = "Access Level:")]
        [Range(1, 10)]
        public int accessLevel { get; set; }

        [Required]
        [Display(Name = "First Name")]
        [StringLength(25)]
        public string FirstName { get; set; }

        [Display(Name = "Middle Name")]
        [StringLength(25)]
        public string MiddleName { get; set; }

        [Required]
        [Display(Name = "Grade")]
        [StringLength(25)]
        public string grade { get; set; }
    }
}

Assignment_5_1_StarterCode/CIS174_TestCoreApp/Controllers/AccessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CIS174_TestCoreApp.Controllers
{
    public class AccessController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Assignment_5_1_StarterCode/CIS174_TestCoreApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CIS174_TestCoreApp.Models;

namespace CIS174_TestCoreApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Assignment_5_1_StarterCode/CIS174_TestCoreApp/Controllers/HouseViewModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CIS174_TestCoreApp.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class HouseController : Controller
    {
        List<String> _houses = new List<string>
        {
            "4",
            "1854",
            "05/28/1973",
            "Carpet"
        };

        List<String> _houses2 = new List<string>
        {
            "3",
            "1675",
            "10/17/2015",
            "Hardwood"
        };

        [HttpGet]
        public ActionResult<IEnumerable<string>> Index()
        {
            return _houses;
        }

        [HttpGet("{Bedrooms}")]
        public ActionResult<int> Get(int Bedrooms)
        {
            return Json(Ok());
        }

        [HttpGet("{SqaureFeet}")]
        public ActionResult<int> get(int SqaureFeet)
        {
            return Ok();

            //return notfound();
        }

        [HttpPost("{HouseViewModel}")]
        public ActionResult<int> Post(int HouseViewModel)
        {
            return Json(StatusCode(201));
        }
    }

    public class ValueModel
    {
    }
}

Assignment_5_1_StarterCode/CIS174_TestCoreApp/Controllers/PersonController.cs
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Threading.Tasks;
//using CIS174_TestCoreApp.Models;
//using Microsoft.AspNetCore.Mvc;

//namespace CIS174_TestCoreApp.Controllers
//{
//    public class PersonController : Controller
//    {
//        public IActionResult Index()
//        {
//            var viewModel = new StudentModel
//            {
//                School = "DMACC"
//            };

//            return View(viewModel);
//        }

//        [HttpPost]
//        public IActionResult Index(StudentModel model)
//        {
//            if (!ModelState.IsValid)
//            {
//                return View(model);
//            }

//            return RedirectToAction("Index", "Home");
//        }
//    }

//    public class CreatePersonViewModel
//    {
//    }
//}

Assignment_5_1_StarterCode/CIS174_TestCoreApp/Controllers/Week7AssignmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CIS174_TestCoreApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace CIS174_TestCoreApp.Controllers
{
    public class Week7AssignmentController : Controller
    {
        public IActionResult Index(CreateAccountViewModel model)
        {
            var viewModel = new CreateAccountViewModel();


            if (!ModelState.IsValid)
            {
                return View(model);
            }
            return RedirectToAction("Index", viewModel);
        }
    }
}

Assignment_5_1_StarterCode/CIS174_TestCoreApp/Views/Access/Index.cshtml
@model CIS174_TestCoreApp.Models.StudentModel

<h2>Enter Access Level</h2>
<form method="post">
    <div class="row">
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-4">
                    @Html.LabelFor(m => m.accessLevel)
                </div>
                <div class="col-md-8">
                    @Html.EditorFor(m => m.accessLevel)
                </div>
                <div class="pull-right col-md-8 text-danger">
                    @Html.ValidationMessageFor(m => m.accessLevel)
                </div>
            </div>
        </div>
    </div>

    <button class="btn btn-primary" type="submit">Submit</button>
</form>

Assignment_5_1_StarterCode/CIS174_TestCoreApp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Assignment_5_1_StarterCode/CIS174_TestCoreApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Assignment_5_1_StarterCode/CIS174_TestCoreApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Assignment_5_1_StarterCode/CIS174_TestCoreApp/Views/HouseViewModel/HouseViewModel.cshtml
@{
    ViewData["Title"] = "HouseViewModel";
}

<h2>HouseViewModel</h2>

Assignment_5_1_StarterCode/CIS174_TestCoreApp/Views/Person/Index.cshtml
@*@model CIS174_TestCoreApp.Models.CreatePersonViewModel

<h2>Create Person</h2>
<form method="post">
    <div class="row">
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-4">
                    @Html.LabelFor(m => m.FirstName)
                </div>
                <div class="col-md-8">
                    @Html.EditorFor(m => m.FirstName)
                </div>
                <div class="pull-right col-md-8 text-danger">
                    @Html.ValidationMessageFor(m => m.FirstName)
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    @Html.LabelFor(m => m.MiddleName)
                </div>
                <div class="col-md-8">
                    @Html.EditorFor(m => m.MiddleName)
                </div>
                <div class="pull-right col-md-8 text-danger">
                    @Html.ValidationMessageFor(m => m.MiddleName)
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    @Html.LabelFor(m => m.LastName)
                </div>
                <div class="col-md-8">
                    @Html.EditorFor(m => m.LastName)
                </div>
                <div class="pull-right col-md-8 text-danger">
                    @Html.ValidationMessageFor(m => m.LastName)
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    @Html.LabelFor(m => m.Age)
                </div>
                <div class="col-md-8">
                    @Html.EditorFor(m => m.Age)
                </div>
                <div class="pull-right col-md-8 text-danger">
                    @Html.ValidationMessageFor(m => m.Age)
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="row">
                <div class="col-md-4">
                    @Html.LabelFor(m => m.Email)
                </div>
                <div class="col-md-8">
                    @Html.EditorFor(m => m.Email)
                </div>
                <div class="pull-right col-md-8 text-danger">
                    @Html.ValidationMessageFor(m => m.Email)
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    @Html.LabelFor(m => m.ConfirmEmail)
                </div>
                <div class="col-md-8">
                    @Html.EditorFor(m => m.ConfirmEmail)
                </div>
                <div class="pull-right col-md-8 text-danger">
                    @Html.ValidationMessageFor(m => m.ConfirmEmail)
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    @Html.LabelFor(m => m.Website)
                </div>
                <div class="col-md-8">
                    @Html.EditorFor(m => m.Website)
                </div>
                <div class="pull-right col-md-8 text-danger">
                    @Html.ValidationMessageFor(m => m.Website)
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    @Html.LabelFor(m => m.School)
                </div>
                <div class="col-md-8">
                    @Html.EditorFor(m => m.School)
                </div>
                <div class="pull-right col-md-8 text-danger">
                    @Html.ValidationMessageFor(m => m.School)
                </div>
            </div>
        </div>
    </div>

    <button class="btn btn-primary" type="submit">Create</button>
</form>*@

Assignment_5_1_StarterCode/CIS174_TestCoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CIS174_TestCoreApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
        }

        .mynav_navbar {
            overflow: hidden;
            background-color: #333;
        }

            .mynav_navbar a {
                float: left;
                font-size: 16px;
                color: white;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }

        .mynav_dropdown {
            float: left;
            overflow: hidden;
        }

            .mynav_dropdown .mynav_dropbtn {
                font-size: 16px;
                border: none;
                outline: none;
                color: white;
                padding: 9px 16px;
                background-color: inherit;
                font-family: inherit;
                margin: 0;
            }

            .mynav_navbar a:hover, .mynav_dropdown:hover .mynav_dropbtn {
                background-color: red;
            }

        .mynav_dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

            .mynav_dropdown-content a {
                float: none;
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
                text-align: left;
            }

                .mynav_dropdown-content a:hover {
                    background-color: #ddd;
                }

        .mynav_dropdown:hover .mynav_dropdown-content {
            display: block;
        }
    </style>

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CIS174_TestCoreApp</a>
            </div>  
            <div class="mynav_navbar">
                <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <a asp-area="" asp-controller="Home" asp-action="About">About</a>
                <a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                <div class="mynav_dropdown">
                    <button class="mynav_dropbtn">
                        Assignments
                        <i class="fa fa-caret-down"></i>
                    </button>
                    <div class="mynav_dropdown-content">
                        <a asp-area="" asp-controller="Access" asp-action="Index">Assignment 6.1</a>
                        <a asp-area="" asp-controller="Week7Assignment" asp-action="Index">Assignment 7.1</a>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - CIS174_TestCoreApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Assignment_5_1_StarterCode/CIS174_TestCoreApp/Views/Week7Assignment/Index.cshtml
@model CIS174_TestCoreApp.Models.CreateAccountViewModel

<h2>Create Account</h2>
<environment include="Production, Staging, Development">
    <div class="warning">You are currently in a non-production environment</div>
</environment>
<form method="post">
    <div class="form-group">
        <label asp-for="FirstName"></label>
        <input class="form-control" asp-for="FirstName" />
        <span asp-validation-for="FirstName"></span>
    </div>
    <div class="form-group">
        <label asp-for="LastName"></label>
        <input class="form-control" asp-for="LastName" />
        <span asp-validation-for="LastName"></span>
    </div>
    <div class="form-group">
        <label for="Age">Age</label>
        <input class="form-control" type="Text"
               id="Age" name="Age" value=""
               data-val="true" data-val-length-max="25"
               data-val-required="Last Name is Required"
               data-val-length="Maximum length is 25"
        <span class="field-validation-valid"
              data-valmsg-for="Age" data-"valmsg-replace="true"></span>
    </div>
    <div class="form-group">
        <label for="DateOfBirth">Date of Birth</label>
        <input class="form-control" type="Text"
               id="DateOfBirth" name="DateOfBirth" value=""
               data-val="true" data-val-length-max="25"
               data-val-required="Last Name is Required"
               data-val-length="Maximum length is 25"
        <span class="field-validation-valid"
              data-valmsg-for="DateOfBirth" data-"valmsg-replace="true"></span>
    </div>
    <div class="form-group">
        <label for="Email">Email</label>
        <input class="form-control" type="Text"
               id="Email" name="Email" value=""
               data-val="true" data-val-length-max="25"
               data-val-required="Last Name is Required"
               data-val-length="Maximum length is 25"
        <span class="field-validation-valid"
              data-valmsg-for="Email" data-"valmsg-replace="true"></span>
    </div>
    <div class="form-group">
        <label for="Password">Password</label>
        <input class="form-control" type="Text"
               id="Password" name="Password" value=""
               data-val="true" data-val-length-max="25"
               data-val-required="Last Name is Required"
               data-val-length="Maximum length is 25"
        <span class="field-validation-valid"
              data-valmsg-for="Password" data-"valmsg-replace="true"></span>
    </div>
    <div class="form-group">
        <label for="ConfirmPassword">Confirm Password</label>
        <input class="form-control" type="Text"
               id="ConfirmPassword" name="ConfirmPassword" value=""
               data-val="true" data-val-length-max="25"
               data-val-required="Last Name is Required"
               data-val-length="Maximum length is 25"
        <span class="field-validation-valid"
              data-valmsg-for="ConfirmPassword" data-"valmsg-replace="true"></span>
    </div>
    <div class="form-group">
        <select id="SelectedValues" name="SelectedValues">
            <option Value="">**Nothing Selected**</option>
            <option value="USA">USA</option>
            <option value="Mexico">Mexico</option>
            <option value="Canada">Canada</option>
        </select>
    </div>

    <button class="btn btn-primary" type="submit">Submit</button>
</form>